# R Operators

## Operators

Operators are used to perform operations on variables and values.

In the example below, we use the + operator to add together two values:

In [38]:
# Example
10 + 5

[1] 15

## R divides the operators in the following groups:

- Arithmetic operators

- Assignment operators

- Comparison operators

- Logical operators

- Miscellaneous operators

## R Arithmetic Operators

Arithmetic operators are used with numeric values to perform common mathematical operations:

Operator	                Name	                                    Example	Try it

+	                        Addition	                                x + y	

-	                        Subtraction	                                x - y	

*	                        Multiplication	                            x * y	

/	                        Division	                                x / y	

^	                        Exponent	                                x ^ y	

%%	                        Modulus (Remainder from division)	        x %% y	

%/%	                        Integer Division	                        x%/%y

# R Assignment Operators

Assignment operators are used to assign values to variables:

In [39]:
# Example
my_var <- 3

my_var <<- 3

3 -> my_var

3 ->> my_var

my_var # print my_var

[1] 3

Note: <<- is a global assigner.

It is also possible to turn the direction of the assignment operator.

x <- 3 is equal to 3 -> x

In [40]:
x <- 10

my_function <- function() {
    x <<- 20
}

my_function()
x

[1] 20

# R Comparison Operators

Comparison operators are used to compare two values:

Operator	                    Name	                        Example	Try it

==	                            Equal	                        x == y	

!=	                            Not equal	                    x != y	

>	                            Greater than	                x > y	

<	                            Less than	                    x < y	

>=	                            Greater than or equal to	    x >= y	

<=	                            Less than or equal to	        x <= y

# R Logical Operators

Logical operators are used to combine conditional statements:

Operator	                        Description

&	                                Element-wise Logical AND operator. Returns TRUE if both elements are TRUE

&&	                                Logical AND operator - Returns TRUE if both statements are TRUE

|	                                Elementwise- Logical OR operator. Returns TRUE if one of the statements is TRUE

||	                                Logical OR operator. Returns TRUE if one of the statements is TRUE

!	                                Logical NOT - Returns FALSE if statement is TRUE

# THE & OPERATOR

In [41]:
x <- c(TRUE, FALSE)
y <- c(TRUE, TRUE)

x & y

[1]  TRUE FALSE

In [42]:
scores <- c(45, 67, 80, 90, 50)

scores > 60 & scores < 85

[1] FALSE  TRUE  TRUE FALSE FALSE

In [43]:
x <- c("apple", "banana", "mango")
y <- c("apple", "grape", "mango")

x==y

(x==y) & (x== "mango")

[1]  TRUE FALSE  TRUE

[1] FALSE FALSE  TRUE

In [44]:
names <- c("John", "Mary", "James", "Peter")

(names == "John") & (names != "Peter")

[1]  TRUE FALSE FALSE FALSE

# THE && OPERATOR

In [45]:
TRUE && FALSE

[1] FALSE

In [76]:
age <- 25
income <- 50000

if (age > 18 && income > 30000) {
    print("Approved")
}

[1] "Approved"

In [47]:
x <- 10

if (x > 5 && x < 20) {
    print("Valid range")
}

[1] "Valid range"

# THE | OPERATOR

In [48]:

sales <- c(100, 250, 400, 150)

sales < 150 | sales > 300

[1]  TRUE FALSE  TRUE FALSE

In [49]:
names <- c("John", "Mary", "Peter", "Jane")

(names == "John") | (names == "Jane")

[1]  TRUE FALSE FALSE  TRUE

In [50]:
data <- data.frame(
    name = c("John", "Mary", "Peter", "Jane"),
    city = c("Lagos", "Abuja", "Lagos", "Kano")
)

data$name == "John" | data$city == "Lagos"

[1]  TRUE FALSE  TRUE FALSE

# THE || OPERATOR

### Simple Logical Values

In [51]:
TRUE || FALSE

[1] TRUE

In [52]:
FALSE || FALSE

[1] FALSE

### Using Vectors

In [53]:
x <- c(FALSE, TRUE)
y <- c(TRUE, FALSE)

x[1] || y[1]

[1] TRUE

### Inside an if Statement

In [54]:
name <- "John"
city <- "Lagos"

if (name == "Peter" || city == "Lagos") {
  print("Condition met")
}

# Summary of the above code
# FALSE || TRUE => TRUE

[1] "Condition met"

### Short-Circuit Behavior

In [55]:
TRUE || print("Hello")

[1] TRUE

Notice:

It does NOT print "Hello".

Why?

Because:

- First value is TRUE

- R stops immediately

- No need to check second condition

`   This is called short-circuit evaluation.    `

### Numeric Conditions

In [56]:
x <- 5

if (x < 3 || x > 4) {
  print("Valid")
}

[1] "Valid"

### Strings with || (Control Logic)

In [57]:
fruit <- "apple"

if (fruit == "banana" || fruit == "apple") {
  print("We have this fruit")
}

[1] "We have this fruit"

# R Miscellaneous Operators

Miscellaneous operators are used to manipulate data:

Operator	                Description	                                            Example

:	                        Creates a series of numbers in a sequence	            x <- 1:10

%in%	                    Find out if an element belongs to a vector	            x %in% y

%*%	                        Matrix Multiplication	                                x <- Matrix1 %*% Matrix2

# Colon Operator : (Creates Sequences)

Example 1: Simple increasing sequence

In [58]:
x <- 1:5
x

[1] 1 2 3 4 5

What this means:

- 1:5 tells R to create a sequence starting from 1 and ending at 5

- It automatically increases by 1

- <- assigns the sequence to variable x

Example 2: Larger range

In [59]:
x <- 10:20
x

 [1] 10 11 12 13 14 15 16 17 18 19 20

What this means:

- 10:20 creates a sequence starting from 10 to 20

- It increases by 1 automatically

- The result is stored in x

Example 3: Decreasing sequence

In [60]:
x <- 5:1
x

[1] 5 4 3 2 1

It creates integer sequences

If you want decimals or different steps, you must use seq() instead:

In [61]:
seq(1, 5, by = 0.5)

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

Example 4: Using in loops

In [62]:
for(i in 1:4){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4

- Step 1: 1:4

Creates a sequence:

1 2 3 4

- Step 2: for(i in 1:4)

This means:

“For each number in the sequence 1, 2, 3, 4… assign it to i and run the code inside the braces.”

- Step 3: print(i)

Each time the loop runs, it prints the current value of i.

Example 5: Creating index positions

In [63]:
letters[1:3]

[1] "a" "b" "c"

What This Means

letters

letters is a built-in R object:

"a" "b" "c" "d" "e" ... "z"


It contains all lowercase alphabets.

1:3

Creates index positions:

1 2 3

letters[1:3]

This means:

“Give me the letters in positions 1, 2, and 3.”

# %in% Operator (Membership Test)

The %in% operator is used for membership testing.

It checks:

“Is this value inside that vector?”

Checks if elements of one vector exist in another.

Example 1: Basic membership

In [64]:
x <- c(1,2,3,4)
2 %in% x

[1] TRUE

Step-by-step Explanation

(1) x <- c(1,2,3,4)

Creates a vector:

Output => 1 2 3 4

(2) 2 %in% x

This asks:

“Is 2 inside the vector x?”

Since 2 is in (1,2,3,4), the result is:

TRUE

### What `%in%` Returns

It always returns TRUE or FALSE.

TRUE → Value exists

FALSE → Value does not exist

Example 2: Multiple values

In [65]:
c(2,5) %in% c(1,2,3,4)

[1]  TRUE FALSE

What This Means

Now we are checking two values at once:

- Is 2 in (1,2,3,4)?

- Is 5 in (1,2,3,4)?

R checks each value separately.

Example 3: With characters

In [66]:
names <- c("John","Mary","Peter")
"Mary" %in% names

[1] TRUE

Example 4: Filtering data

In [67]:
x <- c(10,20,30,40)
x[x %in% c(20,40)]

[1] 20 40

Step 1: Create the vector

x <- c(10, 20, 30, 40)

output = 10 20 30 40

Step 2: Understand This Part

x %in% c(20, 40)

This checks each value in x:

| Value | Is it in (20, 40)? |
| ----- | ------------------ |
| 10    | FALSE              |
| 20    | TRUE               |
| 30    | FALSE              |
| 40    | TRUE               |

So it returns:

FALSE TRUE FALSE TRUE

Step 3: Subsetting

x[ FALSE TRUE FALSE TRUE ]


R keeps only values where condition is TRUE.

So the output is:

20 40

Example 5: Checking missing categories

In [68]:
cities <- c("Lagos","Abuja","Kano")
"Lagos" %in% cities

[1] TRUE

# %*% Operator (Matrix Multiplication)

Used for proper linear algebra multiplication.

Example 1: 2×2 matrices

In [69]:
A <- matrix(c(1,2,3,4), nrow=2)
B <- matrix(c(5,6,7,8), nrow=2)

# 1 3
# 2 4

# 5 7
# 6 8

# Matrix Multiplication

# Multiply rows of A by columns of B

# C|i,j| = ∑(Rowi * Columnj)

# (1 * 5) + (3 * 6) = 5 + 18 = 23 (Row1 * Col1)

# (1 * 7) + (3 * 8) = 7 + 24 = 31 (Row1 * Col2)

# (2 * 5) + (4 * 6) = 10 + 24 = 34 (Row2 * Col1)

# (2 * 7) + (4 * 8) = 14 + 32 = 46 (Row2 * Col2)

A %*% B

     [,1] [,2]
[1,] 23   31
[2,] 34   46

In [70]:
A <- matrix(c(1,2,3,4), nrow=2, byrow = TRUE)
B <- matrix(c(5,6,7,8), nrow=2, byrow = TRUE)

# 1 2
# 3 4

A %*% B

     [,1] [,2]
[1,] 19   22
[2,] 43   50

Example 2: Matrix × Vector

In [71]:
A <- matrix(c(1,2,3,4), nrow=2)
v <- c(1,2)

# 1 3
# 2 4

# 1
# 2

# Matrix multiplication is only valid and possible when the column of the first matrix is equal to the row of the second matrix

# Note: The result of a matrix multiplication will always be  a dimension of the number of rows in the first matrix and the number of column in the second matrix

# Row 1 : (1 * 1) + (3 * 2) = 1 + 6 = 7

# Row 2 : (2 * 1) + (4 * 2) = 2 + 8 = 10

A %*% v

     [,1]
[1,]  7
[2,] 10

Example 3: 3×3 matrix multiplication

In [72]:
A <- matrix(1:9, nrow=3)
B <- matrix(9:1, nrow=3)

A %*% B

     [,1] [,2] [,3]
[1,]  90  54   18
[2,] 114  69   24
[3,] 138  84   30

Example 4: Transpose multiplication

In [73]:
A <- matrix(1:6, nrow=2)
t(A) %*% A

     [,1] [,2] [,3]
[1,]  5   11   17
[2,] 11   25   39
[3,] 17   39   61

Example 5: Identity matrix multiplication

In [74]:
I <- diag(2)
A <- matrix(c(1,2,3,4), nrow=2)

A %*% I

     [,1] [,2]
[1,] 1    3
[2,] 2    4