# R Data Structures

## Data Structures

Data structures are used to store and organize values.

R provides many built-in data structures. Each is used to handle data in different ways:

- Vectors

- Lists

- Matrices

- Arrays

- Data Frames

## R Vectors

### Vectors

A vector is simply a list of items that are of the same type.

To combine the list of items to a vector, use the c() function and separate the items by a comma.

In the example below, we create a vector variable called fruits, that combine strings:

In [166]:
# Example
# Vector of strings
fruits <- c("banana", "apple", "orange") # NOTE: In R, c() means "combine" or "concantenate"
                                         # It is used to put multiple similar values together into a single vector.
                                         # All the values inside c() must be same type (or R will convert them)

# Print fruits
fruits

[1] "banana" "apple"  "orange"

In [167]:
b <- c(1, "A", TRUE)

b
# NOTE: Everything becomes character

[1] "1"    "A"    "TRUE"

In this example, we create a vector that combines numerical values:

In [168]:
# Example
# Vector of numerical values
numbers <- c(1, 2, 3)

# Print numbers
numbers

[1] 1 2 3

To create a vector with numerical values in a sequence, use the : operator:

In [169]:
# Example
# Vector with numerical values in a sequence
numbers <- 1:10

numbers

 [1]  1  2  3  4  5  6  7  8  9 10

You can also create numerical values with decimals in a sequence, but note that if the last element does not belong to the sequence, it is not used:

In [170]:
# Example
# Vector with numerical decimals in a sequence
numbers1 <- 1.5:6.5
numbers1

# Vector with numerical decimals in a sequence where the last element is not used
numbers2 <- 1.5:6.3
numbers2

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

In the example below, we create a vector of logical values:

In [171]:
# Example
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)

log_values

[1]  TRUE FALSE  TRUE FALSE

Vector Length
To find out how many items a vector has, use the length() function:

In [172]:
# Example
fruits <- c("banana", "apple", "orange")

length(fruits)

[1] 3

Sort a Vector
To sort items in a vector alphabetically or numerically, use the sort() function:

In [173]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")
numbers <- c(13, 3, 5, 7, 20, 2)

sort(fruits)  # Sort a string
sort(numbers) # Sort numbers

[1] "apple"  "banana" "lemon"  "mango"  "orange"

[1]  2  3  5  7 13 20

## Access Vectors

You can access the vector items by referring to its index number inside brackets []. The first item has index 1, the second item has index 2, and so on:

In [174]:
# Example
fruits <- c("banana", "apple", "orange")

# Access the first item (banana)
fruits[1]

[1] "banana"

You can also access multiple elements by referring to different index positions with the c() function:

In [175]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access the first and third item (banana and orange)
fruits[c(1, 3)]

[1] "banana" "orange"

You can also use negative index numbers to access all items except the ones specified:

In [176]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access all items except for the first item
fruits[c(-1)]
fruits[-1]

[1] "apple"  "orange" "mango"  "lemon"

[1] "apple"  "orange" "mango"  "lemon"

Change an Item

To change the value of a specific item, refer to the index number:

In [177]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Change "banana" to "pear"
fruits[1] <- "pear"

# Print fruits
fruits

[1] "pear"   "apple"  "orange" "mango"  "lemon"

Replace Multiple Items at Once (By Index)

In [178]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Change "banana" to "pear"
fruits[c(2, 4)] <- c("pear", "grape")

# Print fruits
fruits

[1] "banana" "pear"   "orange" "grape"  "lemon"

Repeat Vectors

To repeat vectors, use the rep() function:

rep() means repeat values in a vector.

In [179]:
# Example
# Repeat each value:

repeat_each <- rep(c(1,2,3), each = 3) # Note: Repeat each individual element three times before moving to the next.

repeat_each

[1] 1 1 1 2 2 2 3 3 3

In [180]:
# Example
# Repeat the sequence of the vector:

repeat_times <- rep(c(1,2,3), times = 3)

repeat_times

[1] 1 2 3 1 2 3 1 2 3

In [181]:
# Example
# Repeat each value independently:

repeat_indepent <- rep(c(1,2,3), times = c(5,2,1)) # This type of repetition is called Element-wise repetition
                                                   # This is because each value is repeated independently based on its corresponding count.
                                                   # Each number repeats based on it's own instruction.

repeat_indepent

[1] 1 1 1 1 1 2 2 3

Generating Sequenced Vectors

One of the examples on top, showed you how to create a vector with numerical values in a sequence with the : operator:

In [182]:
# Example
numbers <- 1:10

numbers

 [1]  1  2  3  4  5  6  7  8  9 10

To make bigger or smaller steps in a sequence, use the seq() function:

In [183]:
# Example
numbers <- seq(from = 0, to = 100, by = 20) # Note: by controls the step size

numbers

[1]   0  20  40  60  80 100

**Note: The seq() function has three parameters: from is where the sequence starts, to is where the sequence stops, and by is the interval of the sequence.**

## R Lists

### Lists

A list in R can contain many different data types inside it. A list is a collection of data which is ordered and changeable.

To create a list, use the list() function:

In [184]:
# Example
# List of strings
thislist <- list("apple", "banana", "cherry")

# Print the list
thislist

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

### Access Lists

You can access the list items by referring to its index number, inside brackets. The first item has index 1, the second item has index 2, and so on:

In [185]:
# Example
thislist <- list("apple", "banana", "cherry")

thislist[1]

[[1]]
[1] "apple"

### Change Item Value

To change the value of a specific item, refer to the index number:

In [186]:
# Example
thislist <- list("apple", "banana", "cherry")
thislist[1] <- "blackcurrant"

# Print the updated list
thislist

[[1]]
[1] "blackcurrant"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

### List Length

To find out how many items a list has, use the length() function:

In [187]:
# Example

thislist <- list("apple", "banana", "cherry")

length(thislist)

[1] 3

### Check if Item Exists

To find out if a specified item is present in a list, use the %in% operator:

In [188]:
# Example
# Check if "apple" is present in the list:

thislist <- list("apple", "banana", "cherry")

"apple" %in% thislist

[1] TRUE

### Add List Items

To add an item to the end of the list, use the append() function:

In [189]:
# Example
# Add "orange" to the list:

thislist <- list("apple", "banana", "cherry")

append(thislist, "orange")

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[4]]
[1] "orange"

To add an item to the right of a specified index, add "after=index number" in the append() function:

In [190]:
# Example
# Add "orange" to the list after "banana" (index 2):

thislist <- list("apple", "banana", "cherry")

append(thislist, "orange", after = 2)

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[4]]
[1] "cherry"

### Remove List Items

You can also remove list items. The following example creates a new, updated list without an "apple" item:

In [191]:
# Example
# Remove "apple" from the list:

thislist <- list("apple", "banana", "cherry")

newlist <- thislist[-1]

# Print the new list
newlist

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

### Range of Indexes

You can specify a range of indexes by specifying where to start and where to end the range, by using the : operator:

In [192]:
# Example
# Return the second, third, fourth and fifth item:

thislist <- list("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

(thislist)[2:5]

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[3]]
[1] "orange"

[[4]]
[1] "kiwi"

### Loop Through a List

You can loop through the list items by using a for loop:

In [193]:
# Example
# Print all items in the list, one by one:

thislist <- list("apple", "banana", "cherry")

for (x in thislist) {
  print(x)
}

[1] "apple"
[1] "banana"
[1] "cherry"

### Join Two Lists

There are several ways to join, or concatenate, two or more lists in R.

The most common way is to use the c() function, which combines two elements together:

In [194]:
# Example
list1 <- list("a", "b", "c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)

list3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

# R Matrices

## Matrices

An R matrix is a two-dimensional data structure in the R programming language that stores elements in rows and columns just like a table in Excel.

A matrix is a two dimensional data set with columns and rows.

In other words, a matrix in R is a collection of elements (usually numbers) arranged in a tabular format with Rows (horizontal) and Columns (vertical).

A column is a vertical representation of data, while a row is a horizontal representation of data.

A matrix can be created with the matrix() function. Specify the nrow and ncol parameters to get the amount of rows and columns:

### Key Features of R Matrices

- All elements in a matrix must be of same type.

- You access elements using [row, column]

In [195]:
# Example
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2) # Note: Remember the c() function is used to concatenate items together.

# Print the matrix
thismatrix

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

I'm telling R Programming to fill row-wise because the deafault in the example above is Column-wise.

In [196]:
# Example
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow = TRUE) # Note: Remember the c() function is used to concatenate items together.

# Print the matrix
thismatrix

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

#### You can also create a matrix with strings:

In [197]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

     [,1]   [,2]
[1,] apple  cherry
[2,] banana orange

## Access Matrix Items

You can access the items by using [ ] brackets. The first number "1" in the bracket specifies the row-position, while the second number "2" specifies the column-position:

In [198]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]

[1] "cherry"

`NOTE: R returns the result as a vector, not as a matrix.`

`NOTE: And a vector in R is always displayed in a straight line.`

#### The whole row can be accessed if you specify a comma after the number in the bracket:

In [199]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]

[1] "banana" "orange"

The whole column can be accessed if you specify a comma before the number in the bracket:

In [200]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]

[1] "cherry" "orange"

## Access More Than One Row

More than one row can be accessed if you use the c() function:

In [201]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]             # c() is used when you want more than one thing.

     [,1]   [,2]   [,3]
[1,] apple  orange pear
[2,] banana grape  melon

        [,1]     [,2]       [,3]
[1,]   apple   orange     pear
[2,]   banana  grape      melon
[3,]   cherry  pineapple  fig

## Access More Than One Column

More than one column can be accessed if you use the c() function:

In [202]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

     [,1]   [,2]
[1,] apple  orange
[2,] banana grape
[3,] cherry pineapple

## Add Rows and Columns

Use the cbind() function to add additional columns in a Matrix:

In [203]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

     [,1]   [,2]      [,3]  [,4]
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry
[3,] cherry pineapple fig   raspberry

`Note: The cells in the new column must be of the same length as the existing matrix.`

#### Use the rbind() function to add additional rows in a Matrix:

In [204]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

     [,1]       [,2]      [,3]
[1,] apple      orange    pear
[2,] banana     grape     melon
[3,] cherry     pineapple fig
[4,] strawberry blueberry raspberry

`Note: The cells in the new row must be of the same length as the existing matrix.`

#### Remove Rows and Columns

Use the c() function to remove rows and columns in a Matrix:

In [205]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix

[1] "mango"     "pineapple"

| Syntax    | Meaning      |
| --------- | ------------ |
| `c(1,2)`  | SELECT items |
| `-c(1,2)` | REMOVE items |

## Check if an Item Exists

To find out if a specified item is present in a matrix, use the %in% (membership) operator:

The Membership operator checks whether a value exists inside a vector, matrix, or list.

In other words, it ascertains if the specified value is inside the data.

In [206]:
# Example
# Check if "apple" is present in the matrix:

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

[1] TRUE

## Number of Rows and Columns

Use the dim() function to find the number of rows and columns in a Matrix:

In [207]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)

[1] 2 2

## Matrix Length

Use the length() function to find the dimension of a Matrix:

In [208]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)

[1] 4

`Total cells in the matrix is the number of rows multiplied by number of columns.`

`In the example above: Dimension = 2*2 = 4.`

## Loop Through a Matrix

You can loop through a Matrix using a for loop. The loop will start at the first row, moving right:

In [209]:
# Example
# Loop through the matrix items and print them:

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"

The output of the above code:

The loop runs like this
| rows | columns | Element Printed |
| ---- | ------- | --------------- |
| 1    | 1       | apple           |
| 1    | 2       | cherry          |
| 2    | 1       | banana          |
| 2    | 2       | orange          |

## Combine two Matrices

Again, you can use the rbind() or cbind() function to combine two or more matrices together:

In [210]:
# Example
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

     [,1]   [,2]
[1,] apple  cherry
[2,] banana grape
[3,] orange pineapple
[4,] mango  watermelon

     [,1]   [,2]   [,3]   [,4]
[1,] apple  cherry orange pineapple
[2,] banana grape  mango  watermelon

# R Arrays

## Arrays

In R Programming, an array is a data structure used to store elements of the same data type in multiple dimensions (more than just rows and columns)

Compared to matrices, arrays can have more than two dimensions.

An R array is like an extension of a matrix that can have 2, 3, or more dimensions.

- 1D  => Vector

- 2D  => Matrix

- 3D+ => Array

We can use the array() function to create an array, and the dim parameter to specify the dimensions:

In [211]:
# Create a 3D array
arr <- array(1:12, dim = c(2,3,2)) # 2 rows, 3 columns, 2 layers
arr

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

In [212]:
# To get the first layer
layer1 <- arr[ , , 1]
layer1

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In [213]:
# To get the second layer
layer2 <- arr[ , , 2]
layer1

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

In [214]:
# To get Row 1, Column 2, and Layer 1
layer1 <- arr[ 1, 2, 1]
layer1

[1] 3

In [215]:
# Example
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

# An array with more than one dimension
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

Example Explained

In the example above we create an array with the values 1 to 24.

How does dim=c(4,3,2) work?

The first and second number in the bracket specifies the amount of rows and columns.

The last number in the bracket specifies how many dimensions we want.

Note: Arrays can only have one data type.

# Access Array Items

You can access the array elements by referring to the index position. You can use the [] brackets to access the desired elements from an array:

In [216]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

multiarray[2, 3, 2]

[1] 22

`The syntax is as follow: array[row position, column position, matrix level]`

#### You can also access the whole row or column from a matrix in an array, by using the c() function:

In [217]:
# Example
thisarray <- c(1:24)

# Access all the items from the first row from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2)) 
multiarray[c(1),,1]     # c(1)    => Row 1
                        # (blank) => All columns
                        # 1  =>  First layer
                        # Summary: Returns Row 1 across all columns in Layer 1

# Access all the items from the first column from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1]     # (blank) => All rows
                        # c(1)    => Column 1
                        # 1       =>  First layer
                        # Summary: Returns Column 1 across all rows in Layer 1

[1] 1 5 9

[1] 1 2 3 4

A comma (,) before c() means that we want to access the column.

A comma (,) after c() means that we want to access the row.

## Check if an Item Exists

To find out if a specified item is present in an array, use the %in% operator:

In [218]:
# Example
# Check if the value "2" is present in the array:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray  # %in% checks: Is this value inside this objects?
                   # R searches through all elements in the array, and if it finds 2 in the array, it results TRUE.

# Check multiple values
c(2, 50) %in% multiarray

# Check if ANY value exists
any(c(50, 2) %in% multiarray)

# check if ALL values exist
all(c(1, 2, 3, 4) %in% multiarray)

[1] TRUE

[1]  TRUE FALSE

[1] TRUE

[1] TRUE

## Amount of Rows and Columns

Use the dim() function to find the amount of rows and columns in an array:

In [219]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

dim(multiarray)

[1] 4 3 2

## Array Length

Use the length() function to find the dimension of an array:

In [220]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

length(multiarray)

[1] 24

## Loop Through an Array

You can loop through the array items by using a for loop:

In [221]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

for(x in multiarray){
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24

# R Data Frames

## Data Frames

An R Data Frame is a table-like structure used to store data in rows and columns similar to Excel Spreadsheet and SQL table. In a simple term, it is a collection of columns, where each column can have different data type.

Data Frames are data displayed in a format as a table.

Data Frames can have different types of data inside it. While the first column can be character, the second and third can be numeric or logical. However, each column should have the same type of data.

Use the data.frame() function to create a data frame:

## Key Characteristics Data Frames

- 2-dimensional (rows x columns)

- Columns can have different data types (numeric, character, logical e.t.c)

- Each column has a name

- Each column is a vector 

- Most commonly used structure in Data Analysis

In [222]:
# Example
# Create a data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Print the data frame
Data_Frame

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45

## Summarize the Data

Use the summary() function to summarize the data from a Data Frame.

It gives a quick statistical overview of each column.

In [223]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame

summary(Data_Frame)

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45

   Training             Pulse          Duration
 Length:3           Min.   :100.0   Min.   :30.0
 Class :character   1st Qu.:110.0   1st Qu.:37.5
 Mode  :character   Median :120.0   Median :45.0
                    Mean   :123.3   Mean   :45.0
                    3rd Qu.:135.0   3rd Qu.:52.5
                    Max.   :150.0   Max.   :60.0

## Access Items

We can use single brackets [ ], double brackets [[ ]] or $ to access columns from a data frame:

In [224]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame[1] # This returns the first column but as a data frame and not a vector

Data_Frame[["Training"]] # Extracts the column as a vector 

Data_Frame$Training # Extracts the column as a vector

  Training
1 Strength
2 Stamina
3 Other

[1] "Strength" "Stamina"  "Other"

[1] "Strength" "Stamina"  "Other"

**NOTE:**

- [] => Give me a table

- [[]] => Give me the actual column values

- $ => Shortcut to get the column

## Add Rows

Use the rbind() function to add new rows in a Data Frame.

It adds rows vertically to a dataframe.

In [225]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Add a new row
New_row_DF <- rbind(Data_Frame, c("Energy", 110, 110))

# Print the new row
New_row_DF

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45
4 Energy   110   110

- NOTE: rbind() stacks data frames like placing one table on top of another.

## Add Columns

Use the cbind() function to add new columns in a Data Frame.

cbind() is used to add new columns to a data frame (side by side) i.e horizontally.

In [226]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Add a new column
New_col_DF <- cbind(Data_Frame, Steps = c(1000, 6000, 2000))

# Print the new column
New_col_DF

  Training Pulse Duration Steps
1 Strength 100   60       1000
2 Stamina  150   30       6000
3 Other    120   45       2000

## Remove Rows and Columns

Use the c() function to remove rows and columns in a Data Frame:

In [227]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Remove the first row and column
Data_Frame_New <- Data_Frame[-c(1), -c(1)] # General strucure in R: data[row, column]
                                           # the first -c(1) => exclude or remove row 1
                                           # the second -c(1) => exclude or remove column 1
# Print the new data frame
Data_Frame_New

  Pulse Duration
2 150   30
3 120   45

## Amount of Rows and Columns

Use the dim() function to find the amount of rows and columns in a Data Frame:

In [228]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

dim(Data_Frame)

[1] 3 3

You can also use the ncol() function to find the number of columns and nrow() to find the number of rows:

In [229]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

ncol(Data_Frame)
nrow(Data_Frame)

[1] 3

[1] 3

## Data Frame Length

Use the length() function to find the number of columns in a Data Frame (similar to ncol()):

In [230]:
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

length(Data_Frame)

[1] 3

## Combining Data Frames

Use the rbind() function to combine two or more data frames in R vertically:

In [231]:
# Example
Data_Frame1 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame2 <- data.frame (
  Training = c("Stamina", "Stamina", "Strength"),
  Pulse = c(140, 150, 160),
  Duration = c(30, 30, 20)
)

New_Data_Frame <- rbind(Data_Frame1, Data_Frame2)
New_Data_Frame

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45
4 Stamina  140   30
5 Stamina  150   30
6 Strength 160   20

### And use the cbind() function to combine two or more data frames in R horizontally:

In [232]:
# Example
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1

  Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300
2 Stamina  150   30       6000  400
3 Other    120   45       2000  300

# R Factors

## Factors

A factor is a data structure in R used to represent categorical data (groups or labels).

Instead of treating values as plain text, R treats them as defined categories with meaning.

Factors are used to categorize data. Examples of factors are:

- Demography: Male/Female

- Music: Rock, Pop, Classic, Jazz

- Training: Strength, Stamina

**To create a factor, use the factor() function and add a vector as argument:**

In [233]:
# Without factors, R sees this just text (character data)
c("Male", "Female", "Male")

[1] "Male"   "Female" "Male"

In [234]:
# R now understands these are categories with possible repetition and structure
factor(c("Male", "Female", "Male"))

[1] Male   Female Male
Levels: Female Male

## Key Reasons We Use Factors

1. To Represent Categorical Data Properly

Real-world data is full of categories:

- Gender

- Product Type

- Region

- Training Type

**Factors help R treat them correctly**

2. To Enable Grouping & Aggregation

3. To Improve Statistical Analysis


4. To Control Order (VERY IMPORTANT)

In [ ]:
factor(c("Low", "Medium", "High"),
       levels = c("Low", "Medium", "High"),
       ordered = TRUE)

[1] Low    Medium High
Levels: Low < Medium < High

In [ ]:
# Example
# Create a factor
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

# Print the factor
music_genre

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz
Levels: Classic Jazz Pop Rock

In [ ]:
# Create a simple character vector
training <- c("Strength", "Stamina", "Strength", "Other")

# Convert to factor
factor_training <- factor(training)

# Print result
factor_training

[1] Strength Stamina  Strength Other
Levels: Other Stamina Strength

You can see from the example above that that the factor has four levels (categories): Classic, Jazz, Pop and Rock.

To only print the levels, use the levels() function:

In [ ]:
# Example
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"

You can also set the levels, by adding the levels argument inside the factor() function:

In [237]:
# Example
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))

levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

# Factor Length

Use the length() function to find out how many items there are in the factor:

In [ ]:
# Example
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

length(music_genre)

[1] 8

## Access Factors

To access the items in a factor, refer to the index number, using [] brackets:

In [ ]:
# Example
# Access the third item:

music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

music_genre[3]

[1] Classic
Levels: Classic Jazz Pop Rock

## Change Item Value

To change the value of a specific item, refer to the index number:

In [238]:
# Example
# Change the value of the third item:

music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

music_genre[3] <- "Pop"

music_genre[3]

music_genre

[1] Pop
Levels: Classic Jazz Pop Rock

[1] Jazz    Rock    Pop     Classic Pop     Jazz    Rock    Jazz
Levels: Classic Jazz Pop Rock

Note that you cannot change the value of a specific item if it is not already specified in the factor. The following example will produce an error:

Example

Trying to change the value of the third item ("Classic") to an item that does not exist/not predefined ("Opera"):

In [ ]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

music_genre[3] <- "Opera"

music_genre[3]

Warning message in `[<-.factor`(`*tmp*`, 3, value = "Opera"):
"invalid factor level, NA generated"

[1] <NA>
Levels: Classic Jazz Pop Rock

However, if you have already specified it inside the levels argument, it will work:

In [ ]:
# Example
# Change the value of the third item:

music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Opera"))

music_genre[3] <- "Opera"

music_genre[3]

[1] Opera
Levels: Classic Jazz Pop Rock Opera